### ISSUE TITLE
关于logger

### ISSUE THREAD

**Issue by Asthestarsfalll** [megvii-research/basecore#1]
请问仓库里的logger是想实现什么样的效果呢？使用场景是什么样的呢
另外[这里](https://github.com/megvii-research/basecore/blob/main/basecore/utils/inspector.py#L19-L38)是不是少了返回值？

**Comment by FateScript** [comment]
caller context用于实现记录上下文，详情参考这个[function](https://github.com/megvii-research/basecore/blob/main/basecore/utils/inspector.py#L47-L78) 以及code所在的文件....

[这行](https://github.com/megvii-research/basecore/blob/main/basecore/utils/inspector.py#L37) 一定能返回结果，不用担心返回值...
